### ISSUE TITLE
core: timeouts too long

### ISSUE THREAD

**Issue by OlegHahm** [cn-uofbasel/ccn-lite#117]
Particular for cases where memory is a scarce resource, it's important to free memory as soon as possible. For these cases, the default timeouts of 40 seconds for interests and 150 seconds for a face are too big.

**Comment by mfrey** [comment]
40 Seconds? Maybe I'm reading it wrong, but 0x0FA is in dec 4000 and since the interest lifetime is in milliseconds this would be 4 seconds. Nevertheless, I think this is an important feature. As far as I can see this is not handled at all (see also #147). 

@cgundogan Have you started working on it? If not I probably would like to give it a try.

**Comment by blacksheeep** [comment]
We had some longer timeouts for NFN, can be reduced now, thanks to R2C. Just commited that code.
