### ISSUE TITLE
question: how to use it create node on different device

### ISSUE THREAD

**Issue by tingxin** [cn-uofbasel/ccn-lite#126]
Hi All, 
I am really newer to ccn, from my understanding,  ccn networking also composed by lots of nodes and those nodes can exchange information to each other, so all the nodes should deploy different device.  i follow the https://github.com/cn-uofbasel/ccn-lite/blob/master/tutorial/tutorial.md, it seems all the nodes created in the same machine. i am confused! 

look forward any kindly man can help me !

thank you again

**Comment by blacksheeep** [comment]
Hi,
this is just a example tutorial, were we used only one machine. Since all
node are communicating by using UDP as transport layer protocol, you can
deploy nodes in different devices - just change the localhost address to
the address of the device you want to connect to.

Best
Christopher



Am 14.07.2017 08:54 schrieb "tingxin" <notifications@github.com>:

Hi All,
I am really newer to ccn, from my understanding, ccn networking also
composed by lots of nodes and those nodes can exchange information to each
other, so all the nodes should deploy different device. i follow the
https://github.com/cn-uofbasel/ccn-lite/blob/master/tutorial/tutorial.md,
it seems all the nodes created in the same machine. i am confused!

look forward any kindly man can help me !

thank you again

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cn-uofbasel/ccn-lite/issues/126>, or mute the thread
