### ISSUE TITLE
[discussion] unit test framework

### ISSUE THREAD

**Issue by blacksheeep** [cn-uofbasel/ccn-lite#184]
Before we integrate unit tests, we have to clarify some Questions.
Questions are:
* Which framework? I would prefer cmake integrated testing.* 
* How to structure the tests?

CMake enables testing from within the cmake file.
Should we add a test case there for every single test. 
Or combine some tests? 
I think combining makes writing tests easier, but not using them.
So I think we should go for max usability?

**Comment by mfrey** [comment]
> CMake enables testing from within the cmake file.

I don't have any in-depth experience with cmake. What does that mean?

> Should we add a test case there for every single test.
> Or combine some tests?

I'm not sure what you exactly mean. You probably have something like
```C
void ccnl_fwd_somefunc_undertest_cond_a_fails(...) { ... } 
void ccnl_fwd_somefunc_undertest_cond_b_fails(...) { ... } 

TestRunner (...) {
   runTest(ccnl_fwd_somefunc_undertest_cond_a_fails);
   runTest(ccnl_fwd_somefunc_undertest_cond_b_fails);
}
```
And you probably want this on a module level. If this let explode your file (nobody wants 100 tests in a single file) you can still introduce directories and put tests over multiple files (e.g. all forwarding related tests are in ``tests/forwarding``). At some point there is probably a single main.c which calls all tests. I don't think you want to manage the tests in the Makefile. That doesn't sound right.

I also think that you want something which allows you to write mocks. If the unit testing framework doesn't support that, there are dedicated libraries for mocking. 

> So I think we should go for max usability?

What do you mean exactly by max usability?

**Comment by blacksheeep** [comment]
ok i will add an example for this. check ccnl-core/test

**Comment by mfrey** [comment]
> i like this kind of testing, since you can simple type make test and get an nice output:

You can define a ``test`` target by yourself for tests and write ``make test``. Usually, the test frameworks I'm aware of give you output about successful and failed tests as well +timing statistics. This is by far not an exclusive feature.

> Additionally, this runs perfect on sempaphore-ci:

This is probably a nice feature. However I'm quite certain that you would get that with every other unit testing framework. The only advantage I can think of that you can easily try to adapt your build system it (add additional logs if build fails, send notifications, etc.)

However, the following is quite bloated
```
    set(TEST_NAME ccnl_core_test_prefix_comp_exact_match)
    add_executable(${TEST_NAME} "test/${TEST_NAME}.c")
    target_link_libraries(${TEST_NAME} ccnl-core ccnl-pkt ccnl-fwd ccnl-nfn ccnl-unix \
      ${OPENSSL_LIBRARIES})
    add_test(NAME ${TEST_NAME} COMMAND ${CMAKE_CURRENT_BINARY_DIR}/${TEST_NAME} 0)
```
The semantics about the expected outcome of a unit test is moved from the unit test to the "meta build system" since it actually runs it. This feels wrong. 

I don't want to make a big fuzz out of it. So maybe the others have some thoughts about it? @cgundogan @cmarxer

**Comment by blacksheeep** [comment]
You are right, we should be able to improve the cmake file, to keep it usable.

**Comment by blacksheeep** [comment]
Ok, there is a way to automatically read and add all files int the test case folder as a test case.
I updated the cmake file
[](https://github.com/cn-uofbasel/ccn-lite/blob/d5a9efebc352ffe10bf848e7502dccd705b480fa/src/ccnl-core/CMakeLists.txt#L20-L32)

**Comment by mfrey** [comment]
So we are going to use ctest?

**Comment by blacksheeep** [comment]
I would say so. I have some examples that work quiet well. And it prevents us from adding another dependency
